// Generate the icon map the AOT Search v2 tree needs, and copy the Codicon font
// in so a webview can draw the tree exactly as the native view does.
//
//   node scripts/build-icons.mjs
//
// A webview cannot use a product icon font or a ThemeIcon - those are workbench
// concepts. It can use a font file it is given, plus a codepoint per icon id. So
// the two sources of truth are:
//   - the d365fo-* codepoints, already declared in package.json
//   - the Codicon codepoints, declared in @vscode/codicons' codicon.css
//
// The generated resources are checked in, so the extension ships self-contained
// and this stays a development-time step. The script fails if the tree can emit
// an icon id that neither source knows about.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const resources = path.join(root, 'resources');
const manifest = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));

/**
 * Every icon id the tree can put on a row. Collected from icon-bearing
 * positions only - a bare `'d365fo-...'` string is not an icon (the same
 * prefixes are reused for contextValue, e.g. `d365fo-category`).
 */
export function iconIdsUsed() {
  const ids = new Set();
  const add = (re, text) => {
    for (const m of text.matchAll(re)) ids.add(m[1]);
  };
  const classic = readFileSync(path.join(root, 'src/classic.ts'), 'utf8');
  // F('Label', 'icon', [folders]) and { id, label, icon }
  add(/F\(\s*'[^']*'\s*,\s*'([a-z0-9-]+)'/g, classic);
  add(/\bicon:\s*'([a-z0-9-]+)'/g, classic);
  const tree = readFileSync(path.join(root, 'src/aotTree.ts'), 'utf8');
  add(/new vscode\.ThemeIcon\('([a-z0-9-]+)'\)/g, tree);
  add(/\bicon(?:Path)?:\s*(?:new vscode\.ThemeIcon\()?['"]([a-z0-9-]+)['"]/g, tree);
  add(/\b(?:memberIcon|typeIcon):\s*'([a-z0-9-]+)'/g, tree);
  add(/iconPathFor\('([a-z0-9-]+)'\)/g, tree);
  return [...ids].sort();
}

/**
 * Codepoints come from `contributes.icons` -> `<theme>.default.fontCharacter`.
 * VS Code's built-in icons are not declared in the manifest, so they come from
 * the Codicon CSS.
 */
function customCodepoints() {
  const out = new Map();
  for (const [id, def] of Object.entries(manifest.contributes.icons ?? {})) {
    const d = def?.default;
    if (typeof d?.fontPath === 'string' && d.fontPath.includes('d365fo-icons.woff') && d.fontCharacter) {
      out.set(id, d.fontCharacter.replace(/^\\u?/, '').toUpperCase());
    }
  }
  return out;
}

/**
 * The published Codicon set has no `puzzle` glyph, which the tree uses for a
 * form's Parts outline node. Everything else resolves exactly; this one is a
 * documented stand-in, recorded in the map as `approx` so the tree can say so
 * instead of pretending.
 */
const SUBSTITUTES = { puzzle: 'symbol-misc' };

function codiconCodepoints() {
  const css = path.join(root, 'node_modules', '@vscode', 'codicons', 'dist', 'codicon.css');
  if (!existsSync(css)) {
    throw new Error('@vscode/codicons is not installed - run: npm install --no-save @vscode/codicons');
  }
  const out = new Map();
  const text = readFileSync(css, 'utf8');
  for (const m of text.matchAll(/\.codicon-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"/g)) {
    out.set(m[1], m[2].toUpperCase());
  }
  return out;
}

const used = iconIdsUsed();
const custom = customCodepoints();
const codicons = codiconCodepoints();

const map = {};
const missing = [];
const substituted = [];
for (const id of used) {
  if (custom.has(id)) {
    map[id] = { font: 'd365fo-icons', code: custom.get(id) };
    continue;
  }
  const want = SUBSTITUTES[id] ?? id;
  if (codicons.has(want)) {
    map[id] = { font: 'codicon', code: codicons.get(want) };
    if (want !== id) {
      // Recorded so the page can mark the row: this glyph is not the real one.
      map[id].approx = want;
      substituted.push(`${id} -> ${want}`);
    }
    continue;
  }
  missing.push(id);
}
if (missing.length > 0) {
  console.error(`ERROR: ${missing.length} icon id(s) the tree can emit have no codepoint:`);
  for (const id of missing) console.error(`  ${id}`);
  process.exit(1);
}

mkdirSync(resources, { recursive: true });
writeFileSync(
  path.join(resources, 'icon-map.json'),
  JSON.stringify(
    {
      note:
        'Icon id -> font + codepoint, for the AOT Search v2 tree (a webview cannot use ThemeIcon ' +
        'or a product icon font). Generated by scripts/build-icons.mjs from package.json ' +
        'contributes.icons and @vscode/codicons/dist/codicon.css. Both fonts ship in resources/.',
      fonts: { 'd365fo-icons': 'd365fo-icons.woff', codicon: 'codicon.ttf' },
      icons: map,
    },
    null,
    1,
  ) + '\n',
);
copyFileSync(
  path.join(root, 'node_modules', '@vscode', 'codicons', 'dist', 'codicon.ttf'),
  path.join(resources, 'codicon.ttf'),
);

const d365fo = Object.values(map).filter((v) => v.font === 'd365fo-icons').length;
console.log(`icon-map.json: ${Object.keys(map).length} ids (${d365fo} custom + ${Object.keys(map).length - d365fo} codicon)`);
if (substituted.length) {
  console.log(`substituted (not in the published Codicon set): ${substituted.join(', ')}`);
}
console.log('copied resources/codicon.ttf');
